//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL3
{
    using System;
    using System.Collections.Generic;
    
    public partial class anime_ilosc_ver2
    {
        public int ID { get; set; }
        public string Nazwa { get; set; }
        public string Status_My { get; set; }
        public string Rodzaj { get; set; }
        public Nullable<int> Progress { get; set; }
        public Nullable<int> Liczba_odcink_w { get; set; }
        public Nullable<int> Score { get; set; }
        public string Genres { get; set; }
        public string Additional_information { get; set; }
    }
}
