//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalAppDBEntities : DbContext
    {
        public MalAppDBEntities()
            : base("name=MalAppDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anime_ilosc_ver2> anime_ilosc_ver2 { get; set; }
        public virtual DbSet<animelist_1538511199_3585579> animelist_1538511199_3585579 { get; set; }
    }
}
